# Generated by Django 4.2.24 on 2025-09-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='sprint',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
