# Generated by Django 4.2.24 on 2025-09-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_task_sprint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='department',
        ),
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.ManyToManyField(blank=True, to='accounts.department'),
        ),
    ]
