# Generated by Django 4.2.24 on 2025-09-30 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_department_customuser_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='event',
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='accounts.project'),
        ),
    ]
