# Generated by Django 4.2.24 on 2025-10-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_subtask_deadline_subtask_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='department',
        ),
        migrations.AddField(
            model_name='project',
            name='department',
            field=models.ManyToManyField(blank=True, to='accounts.department'),
        ),
    ]
