# Generated by Django 4.2.24 on 2025-10-06 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_project_department_project_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('in_review', 'In Review'), ('done', 'Done')], default='todo', max_length=20),
        ),
    ]
