# Generated by Django 4.2.24 on 2025-10-08 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_subtask_assigned_to_subtask_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='subtask',
            name='time_taken',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_subtasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
