# Generated by Django 4.2.24 on 2025-10-08 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_subtask_is_completed_subtask_time_taken_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
        migrations.RemoveField(
            model_name='subtask',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='subtask',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='subtask',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='subtask',
            name='time_taken',
        ),
        migrations.RemoveField(
            model_name='subtask',
            name='total_time',
        ),
        migrations.RemoveField(
            model_name='subtask',
            name='total_time_seconds',
        ),
        migrations.AddField(
            model_name='subtask',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.task'),
        ),
    ]
