# Generated by Django 4.2.24 on 2025-10-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_task_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subtask',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subtask',
            name='time_spent_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
