# Generated by Django 5.2.6 on 2025-10-09 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_subtask_end_time_subtask_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
