# Generated by Django 4.2.24 on 2025-11-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_team_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='accumulated_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
    ]
