# Generated by Django 4.2.24 on 2025-11-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_task_accumulated_time_task_is_paused'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('hod', 'HOD'), ('coordinator', 'Coordinator'), ('staff', 'Staff'), ('student', 'Student')], max_length=15, null=True),
        ),
    ]
