# Generated by Django 4.2.24 on 2025-11-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_team_head_alter_team_members_alter_team_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='keyword',
            field=models.CharField(blank=True, help_text='Short keyword used as prefix for teams', max_length=50, null=True),
        ),
    ]
