# Generated by Django 4.2.24 on 2025-11-25 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_project_status_alter_project_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, help_text='Project end date', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='keyword',
            field=models.CharField(blank=True, help_text='Short keyword used as prefix for teams', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, help_text='Project start date', null=True),
        ),
    ]
