# Generated by Django 4.2.24 on 2025-11-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_remove_project_status_alter_project_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='keyword',
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
