# Generated by Django 4.2.24 on 2025-11-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_remove_project_keyword_alter_project_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='keyword',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
