# Generated by Django 4.2.24 on 2025-11-26 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_project_keyword'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
